version: "3.3"

services:
  web:
    build:
      dockerfile: ./myshop/Dockerfile
    ports:
      - "8000:8000"  # local / container
    volumes:
        - .:/app
    depends_on:
      - db_postgres

  db_postgres:
    container_name: db_postgres
    build: ./postgres
    ports:
      - "5432:5432" # host port 5433 -> linked with container port 5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db_redis:
    container_name: db_redis
    image: redis:7.2.3
    ports:
      - "6379:6379"

  celeryworker:
    container_name: celeryworker
    build:
      dockerfile: ./myshop/DockerfileCelery
    volumes:
      - ./:/opt/celeryworker
    command: celery -A celery_app.celeryapp worker --concurrency 2 -l info
    depends_on:
      - web
      - db_redis

  celeryscheduler:
    container_name: celeryscheduler
    build:
      dockerfile: ./myshop/DockerfileCelery
    volumes:
      - ./:/opt/celeryworker
    command: celery -A celery_app.celeryapp beat -l info
    depends_on:
      - web
      - db_redis

  flower:
    container_name: flower
    image: mher/flower:1.2
    command: celery --broker=redis://db_redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - db_redis
      - celeryworker
      - celeryscheduler

volumes:
  postgres-db-volume: