# Generated by Django 4.2.7 on 2024-01-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='finalizing_time',
        ),
        migrations.AddField(
            model_name='cart',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='finalizing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
