# Generated by Django 4.2.7 on 2024-01-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='close_time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='creation_time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
