# Generated by Django 4.2.7 on 2024-01-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_creation_time_and_more'),
        ('cart', '0003_remove_cart_total_price'),
    ]

    operations = [
    ]
