# Generated by Django 4.2.7 on 2024-01-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_merge_20240122_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
