# Generated by Django 4.2.7 on 2023-12-11 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regtry',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='regtry',
            name='otc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
