# Generated by Django 4.2.7 on 2024-03-07 18:04

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usertwofactorauthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactorauthdata',
            name='gauth_secret',
            field=models.CharField(default=pyotp.random_base32, editable=False, max_length=32),
        ),
    ]
