# Generated by Django 4.2.7 on 2023-12-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='country_brand',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='description_brand',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name_brand',
            new_name='name',
        ),
    ]
