# Generated by Django 4.2.7 on 2023-12-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_created_at'),
        ('product', '0003_brand_product_brand_name'),
    ]

    operations = [
    ]
