# Generated by Django 4.2.7 on 2023-12-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productbrand_alter_product_options_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
