# Generated by Django 4.2.7 on 2023-12-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrand',
            old_name='brand_origin_country',
            new_name='country_of_origin',
        ),
        migrations.RenameField(
            model_name='productbrand',
            old_name='brand_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productbrand',
            old_name='brand_name',
            new_name='name',
        ),
    ]
