# Generated by Django 4.2.7 on 2023-12-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='country_brand',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name_brand',
            new_name='name',
        ),
    ]
