# Generated by Django 4.2.7 on 2024-01-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_fileimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimport',
            name='quantity_new',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='quantity_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
