# Generated by Django 4.2.7 on 2024-01-28 22:11

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_fileimport_errors_fileimport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimport',
            name='errors',
            field=models.JSONField(default=apps.product.models.error_list_default),
        ),
    ]
