# Generated by Django 4.2.7 on 2024-01-29 17:19

import apps.product.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_fileimport_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NEW'), (20, 'SUCCESS'), (30, 'ERROR')], default=apps.product.constants.FileImportStatus['NEW']),
        ),
    ]
